{{- if .Values.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "carbon-kube.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "carbon-kube.labels" . | nindent 4 }}
data:
  # Configuration settings
  threshold: {{ .Values.config.threshold | quote }}
  regions: {{ join "," .Values.config.regions | quote }}
  region-type: {{ .Values.config.regionType | quote }}
  metrics-interval: {{ .Values.config.metricsInterval | quote }}
  debug: {{ .Values.config.debug | quote }}
  
  # Carbon intensity data (populated by poller)
  {{- if .Values.configMap.data }}
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- else }}
  carbon-intensity-data: |
    {
      "timestamp": "1970-01-01T00:00:00Z",
      "zones": {}
    }
  {{- end }}
  
  # Scheduler configuration
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    profiles:
    - schedulerName: carbon-kube-scheduler
      plugins:
        score:
          enabled:
          - name: EmissionPlugin
        filter:
          enabled:
          - name: EmissionPlugin
      pluginConfig:
      - name: EmissionPlugin
        args:
          threshold: {{ .Values.config.threshold }}
          regions: {{ .Values.config.regions | toJson }}
          regionType: {{ .Values.config.regionType | quote }}
          configMapName: {{ include "carbon-kube.configMapName" . }}
          configMapNamespace: {{ .Release.Namespace }}
  
  # Poller configuration
  {{- if .Values.poller.enabled }}
  poller-config.yaml: |
    electricity_maps:
      api_key_secret: {{ include "carbon-kube.secretName" . }}
      api_key_key: electricity-maps-api-key
      cache_timeout: {{ .Values.poller.config.cacheTimeout }}
    noaa:
      api_key_secret: {{ include "carbon-kube.secretName" . }}
      api_key_key: noaa-api-key
    aws:
      region: {{ .Values.poller.config.awsRegion | default "us-west-2" | quote }}
    output:
      configmap_name: {{ include "carbon-kube.configMapName" . }}
      configmap_namespace: {{ .Release.Namespace }}
    regions: {{ .Values.config.regions | toJson }}
  {{- end }}
  
  # RL Tuner configuration
  {{- if .Values.rlTuner.enabled }}
  rl-tuner-config.yaml: |
    model:
      learning_rate: {{ .Values.rlTuner.config.learningRate }}
      batch_size: {{ .Values.rlTuner.config.batchSize }}
      buffer_size: {{ .Values.rlTuner.config.bufferSize }}
      training_steps: {{ .Values.rlTuner.config.trainingSteps }}
    environment:
      threshold_min: 50.0
      threshold_max: 500.0
      reward_scale: 1.0
    output:
      configmap_name: {{ include "carbon-kube.configMapName" . }}
      configmap_namespace: {{ .Release.Namespace }}
      threshold_key: threshold
  {{- end }}
{{- end }}