{{- if and .Values.monitoring.enabled .Values.monitoring.prometheus.rules.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "carbon-kube.fullname" . }}
  namespace: {{ .Values.monitoring.prometheus.rules.namespace | default .Release.Namespace }}
  labels:
    {{- include "carbon-kube.labels" . | nindent 4 }}
    {{- with .Values.monitoring.prometheus.rules.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
    - name: carbon-kube.rules
      interval: 30s
      rules:
        # Carbon intensity metrics
        - record: carbon:intensity:current
          expr: carbon_intensity_gco2_per_kwh
          labels:
            component: carbon-kube
        
        - record: carbon:intensity:average_1h
          expr: avg_over_time(carbon_intensity_gco2_per_kwh[1h])
          labels:
            component: carbon-kube
        
        - record: carbon:intensity:average_24h
          expr: avg_over_time(carbon_intensity_gco2_per_kwh[24h])
          labels:
            component: carbon-kube
        
        # Migration metrics
        - record: carbon:migrations:rate_1h
          expr: rate(carbon_migrations_total[1h])
          labels:
            component: carbon-kube
        
        - record: carbon:migrations:success_rate_1h
          expr: rate(carbon_migrations_successful_total[1h]) / rate(carbon_migrations_total[1h])
          labels:
            component: carbon-kube
        
        # Scheduling metrics
        - record: carbon:scheduling:decisions_rate_1h
          expr: rate(carbon_scheduling_decisions_total[1h])
          labels:
            component: carbon-kube
        
        - record: carbon:scheduling:score_average
          expr: avg(carbon_scheduling_score)
          labels:
            component: carbon-kube
        
        # Energy consumption estimates
        - record: carbon:energy:consumption_kwh_1h
          expr: sum(rate(carbon_energy_consumption_kwh_total[1h]))
          labels:
            component: carbon-kube
        
        - record: carbon:emissions:co2_kg_1h
          expr: sum(rate(carbon_emissions_co2_kg_total[1h]))
          labels:
            component: carbon-kube

    - name: carbon-kube.alerts
      interval: 30s
      rules:
        # High carbon intensity alert
        - alert: CarbonIntensityHigh
          expr: carbon_intensity_gco2_per_kwh > {{ .Values.config.threshold }}
          for: 5m
          labels:
            severity: warning
            component: carbon-kube
          annotations:
            summary: "High carbon intensity detected"
            description: "Carbon intensity is {{ "{{ $value }}" }} gCO2/kWh, above threshold of {{ .Values.config.threshold }} gCO2/kWh in region {{ "{{ $labels.region }}" }}"
        
        # Migration failure rate alert
        - alert: CarbonMigrationFailureRateHigh
          expr: (1 - carbon:migrations:success_rate_1h) > 0.1
          for: 10m
          labels:
            severity: warning
            component: carbon-kube
          annotations:
            summary: "High migration failure rate"
            description: "Migration failure rate is {{ "{{ $value | humanizePercentage }}" }} over the last hour"
        
        # Scheduler plugin down
        - alert: CarbonSchedulerDown
          expr: up{job="carbon-kube-scheduler"} == 0
          for: 1m
          labels:
            severity: critical
            component: carbon-kube
          annotations:
            summary: "Carbon-Kube scheduler is down"
            description: "Carbon-Kube scheduler has been down for more than 1 minute"
        
        # API poller failure
        - alert: CarbonPollerFailing
          expr: increase(carbon_poller_errors_total[1h]) > 5
          for: 5m
          labels:
            severity: warning
            component: carbon-kube
          annotations:
            summary: "Carbon intensity poller is failing"
            description: "Carbon intensity poller has failed {{ "{{ $value }}" }} times in the last hour"
        
        # Stale carbon data
        - alert: CarbonDataStale
          expr: (time() - carbon_data_last_update_timestamp) > 900  # 15 minutes
          for: 5m
          labels:
            severity: warning
            component: carbon-kube
          annotations:
            summary: "Carbon intensity data is stale"
            description: "Carbon intensity data hasn't been updated for {{ "{{ $value | humanizeDuration }}" }}"
        
        # RL tuner performance degradation
        - alert: RLTunerPerformanceDegraded
          expr: carbon_rl_tuner_reward_average < -0.5
          for: 30m
          labels:
            severity: warning
            component: carbon-kube
          annotations:
            summary: "RL tuner performance has degraded"
            description: "RL tuner average reward is {{ "{{ $value }}" }}, indicating poor performance"
        
        # Excessive energy consumption
        - alert: EnergyConsumptionHigh
          expr: carbon:energy:consumption_kwh_1h > 100
          for: 15m
          labels:
            severity: info
            component: carbon-kube
          annotations:
            summary: "High energy consumption detected"
            description: "Energy consumption is {{ "{{ $value }}" }} kWh/hour, consider optimizing workloads"
{{- end }}