{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "carbon-kube.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "carbon-kube.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secret.data.electricity-maps-api-key }}
  electricity-maps-api-key: {{ .Values.secret.data.electricity-maps-api-key | b64enc }}
  {{- else }}
  electricity-maps-api-key: {{ "REPLACE_WITH_YOUR_API_KEY" | b64enc }}
  {{- end }}
  
  {{- if .Values.secret.data.noaa-api-key }}
  noaa-api-key: {{ .Values.secret.data.noaa-api-key | b64enc }}
  {{- else }}
  noaa-api-key: {{ "REPLACE_WITH_YOUR_API_KEY" | b64enc }}
  {{- end }}
  
  {{- if .Values.secret.data.aws-access-key-id }}
  aws-access-key-id: {{ .Values.secret.data.aws-access-key-id | b64enc }}
  {{- else }}
  aws-access-key-id: {{ "REPLACE_WITH_YOUR_ACCESS_KEY" | b64enc }}
  {{- end }}
  
  {{- if .Values.secret.data.aws-secret-access-key }}
  aws-secret-access-key: {{ .Values.secret.data.aws-secret-access-key | b64enc }}
  {{- else }}
  aws-secret-access-key: {{ "REPLACE_WITH_YOUR_SECRET_KEY" | b64enc }}
  {{- end }}
{{- end }}