{{- if .Values.mutator.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: carbon-kube-mutator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "carbon-kube.labels" . | nindent 4 }}
{{- end }}
