{{- if and .Values.rlTuner.enabled .Values.rlTuner.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "carbon-kube.rlTunerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "carbon-kube.labels" . | nindent 4 }}
    app.kubernetes.io/component: rl-tuner
  {{- with .Values.rlTuner.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
