apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: carbon-kube-taint-controller
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get","list","watch","patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: carbon-kube-taint-controller
subjects:
  - kind: ServiceAccount
    name: carbon-kube-taint-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: carbon-kube-taint-controller
  apiGroup: rbac.authorization.k8s.io