{{- if .Values.mutator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbon-kube-mutator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carbon-kube-mutator
  template:
    metadata:
      labels:
        app: carbon-kube-mutator
    spec:
      serviceAccountName: carbon-kube-mutator
      containers:
        - name: mutator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: ["mutator"]
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
{{- end }}
