{{- if .Values.taintController.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbon-kube-taint-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carbon-kube-taint-controller
  template:
    metadata:
      labels:
        app: carbon-kube-taint-controller
    spec:
      serviceAccountName: carbon-kube-taint-controller
      containers:
        - name: controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: ["taintcontroller"]
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
{{- end }}
