apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: carbon-kube-crd-access
rules:
  - apiGroups: ["emission.carbon-kube.io"]
    resources: ["carbonscores"]
    verbs: ["get","list","watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: carbon-kube-crd-access-mutator
subjects:
  - kind: ServiceAccount
    name: carbon-kube-mutator
roleRef:
  kind: Role
  name: carbon-kube-crd-access
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: carbon-kube-crd-access-taintcontroller
subjects:
  - kind: ServiceAccount
    name: carbon-kube-taint-controller
roleRef:
  kind: Role
  name: carbon-kube-crd-access
  apiGroup: rbac.authorization.k8s.io