---
# Carbon Optimization Policy for Production Workloads
apiVersion: carbon.katalyst.io/v1alpha1
kind: CarbonOptimizationPolicy
metadata:
  name: production-optimization
  namespace: production
  labels:
    carbon.katalyst.io/policy-type: "production"
    carbon.katalyst.io/priority: "high"
spec:
  targetNamespace: "production"
  carbonBudget:
    daily: 100.0      # kg CO2 per day
    monthly: 3000.0   # kg CO2 per month
    annual: 36000.0   # kg CO2 per year
  optimizationStrategy: "balanced"
  migrationPolicy:
    enabled: true
    maxMigrationsPerHour: 10
    carbonThresholdDelta: 50.0  # Minimum 50 gCO2/kWh improvement
    excludeWorkloads:
    - "database-primary"
    - "cache-redis"
    - "monitoring-prometheus"
  schedulingPolicy:
    preferGreenNodes: true
    carbonAwareSpread: true
    topologyAware: true
  rlOptimization:
    enabled: true
    trainingSchedule: "0 2 * * *"  # Daily at 2 AM
    explorationRate: 0.1

---
# Carbon Optimization Policy for Development Environment
apiVersion: carbon.katalyst.io/v1alpha1
kind: CarbonOptimizationPolicy
metadata:
  name: development-optimization
  namespace: development
  labels:
    carbon.katalyst.io/policy-type: "development"
    carbon.katalyst.io/priority: "medium"
spec:
  targetNamespace: "development"
  carbonBudget:
    daily: 20.0       # kg CO2 per day
    monthly: 600.0    # kg CO2 per month
    annual: 7200.0    # kg CO2 per year
  optimizationStrategy: "aggressive"
  migrationPolicy:
    enabled: true
    maxMigrationsPerHour: 20
    carbonThresholdDelta: 25.0  # Lower threshold for dev environment
    excludeWorkloads: []
  schedulingPolicy:
    preferGreenNodes: true
    carbonAwareSpread: false
    topologyAware: false
  rlOptimization:
    enabled: true
    trainingSchedule: "0 */6 * * *"  # Every 6 hours
    explorationRate: 0.2

---
# Carbon Optimization Policy for AI/ML Workloads
apiVersion: carbon.katalyst.io/v1alpha1
kind: CarbonOptimizationPolicy
metadata:
  name: aiml-optimization
  namespace: ai-ml
  labels:
    carbon.katalyst.io/policy-type: "ai-ml"
    carbon.katalyst.io/priority: "high"
    carbon.katalyst.io/workload-type: "gpu-intensive"
spec:
  targetNamespace: "ai-ml"
  carbonBudget:
    daily: 500.0      # kg CO2 per day (higher for GPU workloads)
    monthly: 15000.0  # kg CO2 per month
    annual: 180000.0  # kg CO2 per year
  optimizationStrategy: "conservative"  # Careful with expensive GPU workloads
  migrationPolicy:
    enabled: true
    maxMigrationsPerHour: 5   # Lower migration rate for GPU workloads
    carbonThresholdDelta: 100.0  # Higher threshold due to migration cost
    excludeWorkloads:
    - "training-large-model"
    - "inference-production"
  schedulingPolicy:
    preferGreenNodes: true
    carbonAwareSpread: true
    topologyAware: true  # Important for GPU locality
  rlOptimization:
    enabled: true
    trainingSchedule: "0 1 * * 0"  # Weekly on Sunday at 1 AM
    explorationRate: 0.05  # Lower exploration for expensive workloads

---
# Carbon Optimization Policy for Batch Processing
apiVersion: carbon.katalyst.io/v1alpha1
kind: CarbonOptimizationPolicy
metadata:
  name: batch-optimization
  namespace: batch-processing
  labels:
    carbon.katalyst.io/policy-type: "batch"
    carbon.katalyst.io/priority: "low"
    carbon.katalyst.io/scheduling: "flexible"
spec:
  targetNamespace: "batch-processing"
  carbonBudget:
    daily: 50.0       # kg CO2 per day
    monthly: 1500.0   # kg CO2 per month
    annual: 18000.0   # kg CO2 per year
  optimizationStrategy: "aggressive"  # Batch jobs can be more flexible
  migrationPolicy:
    enabled: true
    maxMigrationsPerHour: 50  # High migration rate for batch jobs
    carbonThresholdDelta: 10.0  # Low threshold for batch workloads
    excludeWorkloads: []
  schedulingPolicy:
    preferGreenNodes: true
    carbonAwareSpread: true
    topologyAware: false  # Less critical for batch jobs
  rlOptimization:
    enabled: true
    trainingSchedule: "0 */4 * * *"  # Every 4 hours
    explorationRate: 0.3  # Higher exploration for flexible workloads

---
# Carbon Optimization Policy for Edge Computing
apiVersion: carbon.katalyst.io/v1alpha1
kind: CarbonOptimizationPolicy
metadata:
  name: edge-optimization
  namespace: edge-computing
  labels:
    carbon.katalyst.io/policy-type: "edge"
    carbon.katalyst.io/priority: "medium"
    carbon.katalyst.io/location: "distributed"
spec:
  targetNamespace: "edge-computing"
  carbonBudget:
    daily: 30.0       # kg CO2 per day
    monthly: 900.0    # kg CO2 per month
    annual: 10800.0   # kg CO2 per year
  optimizationStrategy: "balanced"
  migrationPolicy:
    enabled: false  # Limited migration options at edge
    maxMigrationsPerHour: 0
    carbonThresholdDelta: 0.0
    excludeWorkloads: []
  schedulingPolicy:
    preferGreenNodes: true
    carbonAwareSpread: false  # Limited node options at edge
    topologyAware: true
  rlOptimization:
    enabled: false  # Limited compute resources at edge

---
# Global Carbon Optimization Policy
apiVersion: carbon.katalyst.io/v1alpha1
kind: CarbonOptimizationPolicy
metadata:
  name: global-optimization
  namespace: carbon-kube
  labels:
    carbon.katalyst.io/policy-type: "global"
    carbon.katalyst.io/priority: "high"
    carbon.katalyst.io/scope: "cluster-wide"
spec:
  targetNamespace: "*"  # Apply to all namespaces
  carbonBudget:
    daily: 1000.0     # kg CO2 per day (cluster-wide)
    monthly: 30000.0  # kg CO2 per month
    annual: 360000.0  # kg CO2 per year
  optimizationStrategy: "balanced"
  migrationPolicy:
    enabled: true
    maxMigrationsPerHour: 25
    carbonThresholdDelta: 30.0
    excludeWorkloads:
    - "kube-system/*"
    - "katalyst-system/*"
    - "carbon-kube/*"
  schedulingPolicy:
    preferGreenNodes: true
    carbonAwareSpread: true
    topologyAware: true
  rlOptimization:
    enabled: true
    trainingSchedule: "0 3 * * *"  # Daily at 3 AM
    explorationRate: 0.15